name: Motivational Quotes
on:
  push:
    branches:
      - main

jobs:
  motivational_quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get Motivational Quote
        id: get_quote
        run: |
          quotes=(
            "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill"
            "Believe you can and you're halfway there. - Theodore Roosevelt"
            "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt"
            "Your time is limited, don't waste it living someone else's life. - Steve Jobs"
            "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt"
          )
          echo "::set-output name=quote::${quotes[RANDOM % ${#quotes[@]}]}"

      - name: Display Motivational Quote
        run: echo "Motivational Quote:${{ steps.get_quote.outputs.quote }}"
